package com.smartbus.app.presentation.auth.register

val colombiaData = mapOf(
    "Amazonas" to listOf("Leticia", "Puerto Nariño"),
    "Antioquia" to listOf("Medellín", "Bello", "Itagüí", "Envigado", "Rionegro", "Apartadó", "Turbo", "Caucasia", "Santa Fe de Antioquia"),
    "Arauca" to listOf("Arauca", "Saravena", "Tame", "Arauquita"),
    "Atlántico" to listOf("Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Puerto Colombia"),
    "Bolívar" to listOf("Cartagena", "Magangué", "Turbaco", "Arjona", "El Carmen de Bolívar"),
    "Boyacá" to listOf("Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa"),
    "Caldas" to listOf("Manizales", "La Dorada", "Chinchiná", "Villamaría"),
    "Caquetá" to listOf("Florencia", "San Vicente del Caguán", "Cartagena del Chairá"),
    "Casanare" to listOf("Yopal", "Aguazul", "Villanueva", "Paz de Ariporo"),
    "Cauca" to listOf("Popayán", "Santander de Quilichao", "Puerto Tejada"),
    "Cesar" to listOf("Valledupar", "Aguachica", "Codazzi", "Bosconia"),
    "Chocó" to listOf("Quibdó", "Istmina", "Condoto", "Tadó"),
    "Córdoba" to listOf("Montería", "Cereté", "Lorica", "Sahagún", "Montelíbano"),
    "Cundinamarca" to listOf("Soacha", "Chía", "Zipaquirá", "Facatativá", "Girardot", "Fusagasugá"),
    "Guainía" to listOf("Inírida"),
    "Guaviare" to listOf("San José del Guaviare", "Calamar"),
    "Huila" to listOf("Neiva", "Pitalito", "Garzón", "La Plata"),
    "La Guajira" to listOf("Riohacha", "Maicao", "Uribia", "Fonseca"),
    "Magdalena" to listOf("Santa Marta", "Ciénaga", "Fundación", "El Banco"),
    "Meta" to listOf("Villavicencio", "Acacías", "Granada", "Puerto López"),
    "Nariño" to listOf("Pasto", "Tumaco", "Ipiales", "Túquerres"),
    "Norte de Santander" to listOf("Cúcuta", "Ocaña", "Villa del Rosario", "Pamplona"),
    "Putumayo" to listOf("Mocoa", "Puerto Asís", "Orito"),
    "Quindío" to listOf("Armenia", "Calarcá", "La Tebaida", "Montenegro", "Quimbaya", "Circasia"),
    "Risaralda" to listOf("Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"),
    "San Andrés y Providencia" to listOf("San Andrés", "Providencia"),
    "Santander" to listOf("Bucaramanga", "Floridablanca", "Girón", "Barrancabermeja", "San Gil"),
    "Sucre" to listOf("Sincelejo", "Corozal", "Sampués", "Tolú"),
    "Tolima" to listOf("Ibagué", "Espinal", "Melgar", "Honda"),
    "Valle del Cauca" to listOf("Cali", "Palmira", "Buenaventura", "Tuluá", "Cartago", "Buga"),
    "Vaupés" to listOf("Mitú"),
    "Vichada" to listOf("Puerto Carreño")
)
