package com.smartbus.app.navigation

sealed class Screen(val route: String) {
    object Splash : Screen("splash")
    object Welcome : Screen("welcome")
    object Login : Screen("login")
    object Register : Screen("register")
    object RegisterStep2 : Screen("register_step_2")
    object RegisterStep3 : Screen("register_step_3")
    object RegisterLoading : Screen("register_loading")
    object Home : Screen("home")
    object Search : Screen("search")
    object SeatSelection : Screen("seat_selection")
    object Payment : Screen("payment")
    object MyTickets : Screen("my_tickets")
    object Tracking : Screen("tracking")
    object NFCPayment : Screen("nfc_payment")
    object Points : Screen("points")
    object TravelCredit : Screen("travel_credit")
    object Profile : Screen("profile")
    object Notifications : Screen("notifications")
    object PaymentMethods : Screen("payment_methods")
    object HelpSupport : Screen("help_support")
    object Terms : Screen("terms")
}
